[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/the-royal-velvet-sub-logo-bgless.png"
  [headers.values]
    X-Robots-Tag = "noindex, noimageindex"

[[headers]]
  for = "/assets/the-royal-velvet-sub-logo-web.png"
  [headers.values]
    X-Robots-Tag = "noindex, noimageindex"

[[headers]]
  for = "/assets/royal-velvet-logo-transparent.png"
  [headers.values]
    X-Robots-Tag = "noindex, noimageindex"
